// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spkazgromrirvlhyxnho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwa2F6Z3JvbXJpcnZsaHl4bmhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDk1ODksImV4cCI6MjA3NDM4NTU4OX0.xNTG6ARuae-PBX45VqkouyI20GXuDKp2fyMdU9_ff2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});